/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BuildingIndexImport } from './routes/$building/index'
import { Route as BuildingFloorImport } from './routes/$building/$floor'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BuildingIndexRoute = BuildingIndexImport.update({
  id: '/$building/',
  path: '/$building/',
  getParentRoute: () => rootRoute,
} as any)

const BuildingFloorRoute = BuildingFloorImport.update({
  id: '/$building/$floor',
  path: '/$building/$floor',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$building/$floor': {
      id: '/$building/$floor'
      path: '/$building/$floor'
      fullPath: '/$building/$floor'
      preLoaderRoute: typeof BuildingFloorImport
      parentRoute: typeof rootRoute
    }
    '/$building/': {
      id: '/$building/'
      path: '/$building'
      fullPath: '/$building'
      preLoaderRoute: typeof BuildingIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$building/$floor': typeof BuildingFloorRoute
  '/$building': typeof BuildingIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$building/$floor': typeof BuildingFloorRoute
  '/$building': typeof BuildingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$building/$floor': typeof BuildingFloorRoute
  '/$building/': typeof BuildingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$building/$floor' | '/$building'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$building/$floor' | '/$building'
  id: '__root__' | '/' | '/$building/$floor' | '/$building/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildingFloorRoute: typeof BuildingFloorRoute
  BuildingIndexRoute: typeof BuildingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildingFloorRoute: BuildingFloorRoute,
  BuildingIndexRoute: BuildingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$building/$floor",
        "/$building/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$building/$floor": {
      "filePath": "$building/$floor.tsx"
    },
    "/$building/": {
      "filePath": "$building/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
